# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c1d1b04a13582dd6845f94e561d96d7ebc44e56e6c5a72010954003ee7fbc9bdb94dde8d9a3bdbd3b3ffd749ad2cd28fe45a2104d764245a47b971f252124b0

test:
  secret_key_base: fb82733e438a09acfd5959959f7221dea8e0f3a3217dbf0b7093957fa15eab097bcd3fb1f666528e5e71a71b31294f504c4d34d935548c2e7bd32cecfe2b6e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
